package ru.bmstu.gateway.dto.enums.logStatuses;


public enum ActionType {
    REGISTRATION("REGISTRATION"),
    AUTHORIZATION("AUTHORIZATION"),
    ALL_HOTELS("ALL_HOTELS"),
    RESERVATIONS_BY_USER("RESERVATIONS_BY_USER"),
    RESERVATIONS_BY_USERNAME("RESERVATIONS_BY_USERNAME"),
    RESERVATION_BY_USERNAME_RESERVATIONUID("RESERVATION_BY_USERNAME_RESERVATIONUID"),
    CREATE_RESERVATION("CREATE_RESERVATION"),
    DELETE_RESERVATION("DELETE_RESERVATION"),
    LOYALTY_INFO_BY_USERNAME("LOYALTY_INFO_BY_USERNAME");

    private String name;

    ActionType(String name) {
        this.name = name;
    }
}
