name: Build Project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build and run unit tests

#      - name: Build images
#        timeout-minutes: 10
#        run: docker compose build

#      - name: Run containers
#        timeout-minutes: 5
#        run: |
#          docker compose up -d
#          ./scripts/wait-script.sh
#        env:
#          WAIT_PORTS: 8080,8070,8060,8050

#      - name: GitHub auto grader mark
#        uses: Romanow/google-sheet-autograder-marker@v1.0
#        with:
#          google_token: ${{secrets.GOOGLE_API_KEY}}
#          sheet_id: ""
#          homework_number: 1
#          user_column: 'D'
#          column_offset: 'F'
#          mark: "'+"

#      - name: Stop containers
#        if: always()
#        continue-on-error: true
#        run: docker compose down -v